name: fvv
description: "Fresh View for Viewer (FVV/FW/废物/廢物). Lightweight text formatting."
version: 1.0.0+10
repository: https://gitcode.com/OutOfMemories-WorkGroup/FVV
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  test: ^1.26.2
  very_good_analysis: ^9.0.0