semi: false
singleQuote: true
jsxSingleQuote: true
trailingComma: none
bracketSameLine: true
arrowParens: avoid

importOrder: ['<THIRD_PARTY_MODULES>', '^@(?!@|/)', '^#', '^@@/', '^~~/', '^@/', '^~/', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true

plugins:
  - '@trivago/prettier-plugin-sort-imports'
