printWidth: 127
useTabs: true
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: none
bracketSpacing: false
bracketSameLine: true
arrowParens: avoid

importOrder: ['<THIRD_PARTY_MODULES>', '^@(.*)/(.*)$', '^@/(.*)$', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true

plugins:
  - '@trivago/prettier-plugin-sort-imports'